### ISSUE TITLE
Broken - can't load tab separated CSV's

### ISSUE THREAD

**Issue by paulsop** [alexscheelmeyer/csv-streamer#5]
Was working with earlier version. Now breaks with:

events.js:187
      throw err;
     ^
Error: Unhandled "error" event. (Error at line 2 (Expected 15 values, but got 13))

My file is simple -- just tab delimited '\t' and headers.

If there are two tabs in a row, it appears to crash (i.e. if there is an empty cell).

Earlier in November it worked fine.

**Comment by alexscheelmeyer** [comment]
Hi Paul,
Thank you for reporting this - I made a testcase to verify the issue and have pushed a fix for it. Please try v2.0.1, it should be fixed now.

**Comment by paulsop** [comment]
Thanks :)
